spring:
  application:
    name: practicum-admin-portal


practicum:
  api:
    base-url: "https://mypracticum-backend-1036236504607.me-west1.run.app/api/v1"
    jwt: ${PRACTICUM_API_JWT}


server:
  port: 8090


