port: "8080"

auth:
  # non-sensitive defaults
  jwtIssuer:      "mypracticum"
  jwtTTL:         "2400h"          # 100 days      
smoove:
  baseURL:        "https://rest.smoove.io/v1/"
otp:
  codeLength:          6
  expiry:             "5m"
  sendWindow:         "10s"
  globalOTPWindow:    "3s"
smtp:
  host: "mail.temurot.com"
  port: 465
  username: "practicum@temurot.com"
  # password should be provided via environment (SMTP_PASS) or .env for security
  from: "practicum@temurot.com"