port: "8080"

auth:
  # non-sensitive defaults
  jwtIssuer:      "mypracticum"
  jwtTTL:         "168h"               
smoove:
  baseURL:        "https://rest.smoove.io/v1/"
otp:
  codeLength:          6
  expiry:             "5m"
  sendWindow:         "2m"
  globalOTPWindow:    "3s"